# Generated by Django 3.1 on 2020-12-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201219_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='header',
            new_name='user_agent',
        ),
    ]
