# Generated by Django 3.1 on 2021-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201219_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, default=models.EmailField(max_length=255, unique=True, verbose_name='email'), max_length=254, null=True),
        ),
    ]
