export const options = [
  { key: 1, label: 'Polish', value: 'Polish' },
  { key: 2, label: 'English', value: 'English' },
];

export const analysisContent = [
  {
    title: 'Basic info',
    label1: 'Keyword',
    label2: 'Language',
    label3: '',
    label4: '',
    text1: 'Lorem ipsum',
    text2: 'Polish',
    text3: '',
    text4: '',
  },
  {
    title: 'Pytrends keywords',
    label1: '',
    label2: '',
    label3: '',
    label4: '',
    text1:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.",
    text2: '',
    text3: '',
    text4: '',
  },
  {
    title: 'Internal links',
    label1: '',
    label2: '',
    label3: '',
    label4: '',
    text1: '<String>',
    text2: '<String>',
    text3: '<String>',
    text4: '',
  },
  {
    title: 'SERP keywords',
    label1: '',
    label2: '',
    label3: '',
    label4: '',
    text1: '<String>',
    text2: '<String>',
    text3: '<String>',
    text4: '',
  },
  {
    title: 'Google suggestions questions',
    label1: 'Question',
    label2: 'Results',
    label3: '',
    label4: '',
    text1: 'Lorem Ipsum',
    text2: '<String>',
    text3: '',
    text4: '',
  },
  {
    title: 'Google suggestions prepositions',
    label1: 'Preposition',
    label2: 'Results',
    label3: '',
    label4: '',
    text1: 'Results',
    text2: '<String>',
    text3: '<String>',
    text4: '',
  },
  {
    title: 'Google suggestions comparisons',
    label1: 'comparison',
    label2: 'Results',
    label3: '',
    label4: '',
    text1: 'Results',
    text2: '<String>',
    text3: '<String>',
    text4: '',
  },
  {
    title: 'Google suggestions alphabeticals',
    label1: 'Letter',
    label2: 'Results',
    label3: 'Letter',
    label4: 'Results',
    text1: 'lorem ipsum',
    text2: '<String>',
    text3: '<String>',
    text4: '<String>',
  },
];
