# Generated by Django 3.1 on 2020-12-17 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_check', models.TextField(blank=True, max_length=15000)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('page_title', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True, max_length=280)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content analysis',
                'verbose_name_plural': 'Users content analysis',
            },
        ),
    ]
