# Generated by Django 3.1 on 2021-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentanalysis',
            options={'verbose_name': 'Content analysis', 'verbose_name_plural': 'Content analysis'},
        ),
    ]
