# Generated by Django 3.1 on 2021-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_analysis', '0002_auto_20210118_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentanalysis',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contentanalysis',
            name='meta_description',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='contentanalysis',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentanalysis',
            name='text_to_check',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
    ]
