export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const LOGIN_MESSAGE = 'LOGIN_MESSAGE';
export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

export const CREATE = 'CREATE';
export const REQUEST_KEYPLANNER_DATA = 'REQUEST_KEYPLANNER_DATA';
export const RECEIVE_KEYPLANNER_DATA = 'RECEIVE_KEYPLANNER_DATA';

export const REQUEST_CHECK_DATA = 'REQUEST_CHECK_DATA';
export const RECEIVE_CHECK_DATA = 'RECEIVE_CHECK_DATA';
export const CLEAR_CHECK_DATA = 'CLEAR_CHECK_DATA';

export const REQUEST_ANALYSE_DATA = 'REQUEST_ANALYSE_DATA';
export const RECEIVE_ANALYSE_DATA = 'RECEIVE_ANALYSE_DATA';
export const CLEAR_ANALYSE_DATA = 'CLEAR_ANALYSE_DATA';

export const REQUEST_WEBSITEINFO_DATA = 'REQUEST_WEBSITEINFO_DATA';
export const RECEIVE_WEBSITEINFO_DATA = 'RECEIVE_WEBSITEINFO_DATA';
export const CLEAR_WEBSITEINFO_ERROR = 'CLEAR_WEBSITEINFO_ERROR';

export const REQUEST_AUDITCHECK_DATA = 'REQUEST_AUDITCHECK_DATA';
export const RECEIVE_AUDITCHECK_DATA = 'RECEIVE_AUDITCHECK_DATA';
export const CLEAR_AUDITCHECK_ERROR = 'CLEAR_AUDITCHECK_ERROR';

export const REQUEST_CREATEAUDIT_DATA = 'REQUEST_CREATEAUDIT_DATA';
export const RECEIVE_CREATEAUDIT_DATA = 'RECEIVE_CREATEAUDIT_DATA';
export const CLEAR_CREATEAUDIT_DATA = 'CLEAR_CREATEAUDIT_DATA';

export const REQUEST_WEBSITEANALYSIS_DATA = 'REQUEST_WEBSITEANALYSIS_DATA';
export const RECEIVE_WEBSITEANALYSIS_DATA = 'RECEIVE_WEBSITEANALYSIS_DATA';
export const CLEAR_WEBSITEANALYSIS_DATA = 'CLEAR_WEBSITEANALYSIS_DATA';

export const REQUEST_KEYWORDANALYSIS_DATA = 'REQUEST_KEYWORDANALYSIS_DATA';
export const RECEIVE_KEYWORDANALYSIS_DATA = 'RECEIVE_KEYWORDANALYSIS_DATA';

export const REQUEST_CONTACTEMAILCHANGE_DATA =
  'REQUEST_CONTACTEMAILCHANGE_DATA';
export const RECEIVE_CONTACTEMAILCHANGE_DATA =
  'RECEIVE_CONTACTEMAILCHANGE_DATA';
export const CLEAR_CONTACTEMAILCHANGE_DATA = 'CLEAR_CONTACTEMAILCHANGE_DATA';

export const REQUEST_USEREMAILCHANGE_DATA = 'REQUEST_USEREMAILCHANGE_DATA';
export const RECEIVE_USEREMAILCHANGE_DATA = 'RECEIVE_USEREMAILCHANGE_DATA';
export const CLEAR_USEREMAILCHANGE_DATA = 'CLEAR_USEREMAILCHANGE_DATA';

export const REQUEST_USERAGENTCHANGE_DATA = 'REQUEST_USERAGENTCHANGE_DATA';
export const RECEIVE_USERAGENTCHANGE_DATA = 'RECEIVE_USERAGENTCHANGE_DATA';
export const CLEAR_USERAGENTCHANGE_DATA = 'CLEAR_USERAGENTCHANGE_DATA';
