export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const LOGIN_MESSAGE = 'LOGIN_MESSAGE';
export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

export const CREATE = 'CREATE';
export const REQUEST_KEYPLANNER_DATA = 'REQUEST_KEYPLANNER_DATA';
export const RECEIVE_KEYPLANNER_DATA = 'RECEIVE_KEYPLANNER_DATA';

export const REQUEST_CHECK_DATA = 'REQUEST_CHECK_DATA';
export const RECEIVE_CHECK_DATA = 'RECEIVE_CHECK_DATA';
export const CLEAR_CHECK_DATA = 'CLEAR_CHECK_DATA';

export const REQUEST_ANALYSE_DATA = 'REQUEST_ANALYSE_DATA';
export const RECEIVE_ANALYSE_DATA = 'RECEIVE_ANALYSE_DATA';
export const CLEAR_ANALYSE_DATA = 'CLEAR_ANALYSE_DATA';

export const REQUEST_WEBSITEINFO_DATA = 'REQUEST_WEBSITEINFO_DATA';
export const RECEIVE_WEBSITEINFO_DATA = 'RECEIVE_WEBSITEINFO_DATA';
export const CLEAR_WEBSITEINFO_ERROR = 'CLEAR_WEBSITEINFO_ERROR';

export const REQUEST_AUDITCHECK_DATA = 'REQUEST_AUDITCHECK_DATA';
export const RECEIVE_AUDITCHECK_DATA = 'RECEIVE_AUDITCHECK_DATA';
export const CLEAR_AUDITCHECK_ERROR = 'CLEAR_AUDITCHECK_ERROR';

export const REQUEST_CREATEAUDIT_DATA = 'REQUEST_CREATEAUDIT_DATA';
export const RECEIVE_CREATEAUDIT_DATA = 'RECEIVE_CREATEAUDIT_DATA';
export const CLEAR_CREATEAUDIT_DATA = 'CLEAR_CREATEAUDIT_DATA';

export const REQUEST_WEBSITEANALYSIS_DATA = 'REQUEST_WEBSITEANALYSIS_DATA';
export const RECEIVE_WEBSITEANALYSIS_DATA = 'RECEIVE_WEBSITEANALYSIS_DATA';
export const CLEAR_WEBSITEANALYSIS_DATA = 'CLEAR_WEBSITEANALYSIS_DATA';

export const REQUEST_KEYWORDANALYSIS_DATA = 'REQUEST_KEYWORDANALYSIS_DATA';
export const RECEIVE_KEYWORDANALYSIS_DATA = 'RECEIVE_KEYWORDANALYSIS_DATA';
export const CLEAR_KEYWORDANALYSIS_DATA = 'CLEAR_KEYWORDANALYSIS_DATA';

export const REQUEST_CONTACTEMAILCHANGE_DATA =
  'REQUEST_CONTACTEMAILCHANGE_DATA';
export const RECEIVE_CONTACTEMAILCHANGE_DATA =
  'RECEIVE_CONTACTEMAILCHANGE_DATA';
export const CLEAR_CONTACTEMAILCHANGE_DATA = 'CLEAR_CONTACTEMAILCHANGE_DATA';

export const REQUEST_USEREMAILCHANGE_DATA = 'REQUEST_USEREMAILCHANGE_DATA';
export const RECEIVE_USEREMAILCHANGE_DATA = 'RECEIVE_USEREMAILCHANGE_DATA';
export const CLEAR_USEREMAILCHANGE_DATA = 'CLEAR_USEREMAILCHANGE_DATA';

export const REQUEST_USERAGENTCHANGE_DATA = 'REQUEST_USERAGENTCHANGE_DATA';
export const RECEIVE_USERAGENTCHANGE_DATA = 'RECEIVE_USERAGENTCHANGE_DATA';
export const CLEAR_USERAGENTCHANGE_DATA = 'CLEAR_USERAGENTCHANGE_DATA';

export const REQUEST_USEREPASSWORDCHANGE_DATA =
  'REQUEST_USEREPASSWORDCHANGE_DATA';
export const RECEIVE_USEREPASSWORDCHANGE_DATA =
  'RECEIVE_USEREPASSWORDCHANGE_DATA';
export const CLEAR_USEREPASSWORDCHANGE_DATA = 'CLEAR_USEREPASSWORDCHANGE_DATA';

export const REQUEST_NEWS_DATA = 'REQUEST_NEWS_DATA';
export const RECEIVE_NEWS_DATA = 'RECEIVE_NEWS_DATA';

export const REQUEST_ARTICLES_DATA = 'REQUEST_ARTICLES_DATA';
export const RECEIVE_ARTICLES_DATA = 'RECEIVE_ARTICLES_DATA';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CLEAR_EDIT_ARTICLE = 'CLEAR_EDIT_ARTICLE';

export const REQUEST_KEYWORDS_DATA = 'REQUEST_KEYWORDS_DATA';
export const RECEIVE_KEYWORDS_DATA = 'RECEIVE_KEYWORDS_DATA';
export const DELETE_KEYWORD = 'DELETE_KEYWORD';
export const GET_KEYWORD = 'GET_KEYWORD';
export const CLEAR_KEYWORD_CHECK = 'CLEAR_KEYWORD_CHECK';

export const REQUEST_AUDITS_DATA = 'REQUEST_AUDITS_DATA';
export const RECEIVE_AUDITS_DATA = 'RECEIVE_AUDITS_DATA';
export const DELETE_AUDIT = 'DELETE_AUDIT';
export const GET_AUDIT = 'GET_AUDIT';
export const CLEAR_AUDIT_CHECK = 'CLEAR_AUDIT_CHECK';

export const REQUEST_SEARCH_DATA = 'REQUEST_SEARCH_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
