export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const LOGIN_MESSAGE = 'LOGIN_MESSAGE';
export const REGISTER_MESSAGE = 'REGISTER_MESSAGE';
export const CLEAR_REGISTER = 'CLEAR_REGISTER';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

export const CREATE = 'CREATE';
export const REQUEST_KEYPLANNER_DATA = 'REQUEST_KEYPLANNER_DATA';
export const RECEIVE_KEYPLANNER_DATA = 'RECEIVE_KEYPLANNER_DATA';

export const REQUEST_CHECK_DATA = 'REQUEST_CHECK_DATA';
export const RECEIVE_CHECK_DATA = 'RECEIVE_CHECK_DATA';
export const CLEAR_CHECK_DATA = 'CLEAR_CHECK_DATA';

export const REQUEST_ANALYSE_DATA = 'REQUEST_ANALYSE_DATA';
export const RECEIVE_ANALYSE_DATA = 'RECEIVE_ANALYSE_DATA';
export const CLEAR_ANALYSE_DATA = 'CLEAR_ANALYSE_DATA';

export const REQUEST_WEBSITEINFO_DATA = 'REQUEST_WEBSITEINFO_DATA';
export const RECEIVE_WEBSITEINFO_DATA = 'RECEIVE_WEBSITEINFO_DATA';
