# Generated by Django 3.1 on 2020-12-16 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
                ('lang', models.CharField(choices=[('pl', 'Polski'), ('en', 'Angielski')], default='pl', max_length=6)),
                ('googleKeywords', models.JSONField(blank=True, null=True)),
                ('pytrendsKeywords', models.JSONField(blank=True, null=True)),
                ('serpKeywords', models.JSONField(blank=True, null=True)),
                ('googleSuggestionsQuestions', models.JSONField(blank=True, null=True)),
                ('googleSuggestionsPrepositions', models.JSONField(blank=True, null=True)),
                ('googleSuggestionsComparisons', models.JSONField(blank=True, null=True)),
                ('googleSuggestionsAlphabeticals', models.JSONField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keyword analysis',
            },
        ),
    ]
