# Generated by Django 3.1 on 2021-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_planner', '0004_auto_20210114_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordplanner',
            options={'verbose_name': 'Keyword analysis', 'verbose_name_plural': 'Keyword analysis'},
        ),
    ]
