# Generated by Django 3.1 on 2021-01-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_planner', '0005_auto_20210118_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordplanner',
            name='language',
            field=models.CharField(choices=[('Polish', 'Polish'), ('English', 'English')], default='pl', max_length=8),
        ),
    ]
