# Generated by Django 3.1 on 2021-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': 'Audit', 'verbose_name_plural': 'Audit'},
        ),
    ]
